### ISSUE TITLE
Review 1: Program menerima input yang salah

### ISSUE THREAD

**Issue by priyandari** [ryanferza/tagihan_pulsa#2]
Input yang salah tetapi diterima.
Perhatikan kejanggalan pada inputan program ini
![Capture3](https://user-images.githubusercontent.com/4914090/83825061-64bb6f80-a702-11ea-82f4-af75209c868b.PNG)

**Comment by ryanferza** [comment]
Untuk issue ini sudah kami perbaiki pak, dapat direview kembali. Kami merevisi program agar langsung menghitung setiap minggunya tanpa perlu para pelanggan menginput sendiri
