### ISSUE TITLE
Review 1: Data lama yang sudah tersimpan

### ISSUE THREAD

**Issue by priyandari** [ryanferza/tagihan_pulsa#3]
Sebaiknya jangan dihapus, tetapi dapat ditampilkan lagi ..
Kalau dihapus apa gunakan ada file ? cukup simpan di memori komputer saja

**Comment by priyandari** [comment]
Ini belum diselesaikan !
File yang telah disimpan belum bisa ditampilkan lagi. Padahal saat menjalankan program, Nama sudah pernah ada, mestinya ya disajikan dahulu data yang lama yang pernah dibuat oleh si pengguna yang nama filenya telah ada

**Comment by ryanferza** [comment]
Untuk issue ini sudah kami perbaiki pak, dapat direview kembali. Kami membuat program menjadi 2 menu, salah satu menunya yaitu dapat mengecek data dari csv yang telah diinputkan sebelumnya dan dapat ditampilkan kembali pada menu ini.
