### ISSUE TITLE
Inputan urutan minggu tagihan

### ISSUE THREAD

**Issue by priyandari** [ryanferza/tagihan_pulsa#4]
( jika yang diinput bukan minggu pertama maka program tidak akan berjalan )

Kalau begitu pengguna tidak usah disuruh input, kan jadi bingung.. disuruh input mnggu ke tetapi harus ngurut dari minggu ke 1.

harusnya fleksibel mau minggu ke berapa dahulu yang diinput

**Comment by ryanferza** [comment]
Untuk issue ini sudah kami perbaiki pak, dengan menjadikan para pelanggan tidak perlu menginput minggu keberapa, namun diganti dengan program yang langsung menghitung tagihan setiap minggu sesuai yang diinputkan.
